### ISSUE TITLE
Support multiple commands per input, separated by semi-colons.

### ISSUE THREAD

**Issue by ndouglas** [saltshore/saltshore#16]
### User Story

As a player, I want to enter multiple commands at once, separated by semi-colons, so that I can get from Point A to Point B in a hurry.

### Tasks

- [x] Separate input by semi-colons and treat each as a separate command.
- [x] Dequeue and handle a single "command" on each iteration of the game loop.
- [x] Clear the input queue if a command is invalid.

### Acceptance Criteria

- [x] Input supports multiple commands, separated by semi-colons.
